// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: played.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SendPlayedRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Game                 string   `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPlayedRequest) Reset()         { *m = SendPlayedRequest{} }
func (m *SendPlayedRequest) String() string { return proto.CompactTextString(m) }
func (*SendPlayedRequest) ProtoMessage()    {}
func (*SendPlayedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{0}
}
func (m *SendPlayedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendPlayedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendPlayedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SendPlayedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPlayedRequest.Merge(dst, src)
}
func (m *SendPlayedRequest) XXX_Size() int {
	return m.Size()
}
func (m *SendPlayedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPlayedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPlayedRequest proto.InternalMessageInfo

func (m *SendPlayedRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SendPlayedRequest) GetGame() string {
	if m != nil {
		return m.Game
	}
	return ""
}

type GameEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dur                  int32    `protobuf:"varint,2,opt,name=dur,proto3" json:"dur,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameEntry) Reset()         { *m = GameEntry{} }
func (m *GameEntry) String() string { return proto.CompactTextString(m) }
func (*GameEntry) ProtoMessage()    {}
func (*GameEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{1}
}
func (m *GameEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GameEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEntry.Merge(dst, src)
}
func (m *GameEntry) XXX_Size() int {
	return m.Size()
}
func (m *GameEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEntry.DiscardUnknown(m)
}

var xxx_messageInfo_GameEntry proto.InternalMessageInfo

func (m *GameEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameEntry) GetDur() int32 {
	if m != nil {
		return m.Dur
	}
	return 0
}

type GameEntryPublic struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dur                  string   `protobuf:"bytes,2,opt,name=dur,proto3" json:"dur,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameEntryPublic) Reset()         { *m = GameEntryPublic{} }
func (m *GameEntryPublic) String() string { return proto.CompactTextString(m) }
func (*GameEntryPublic) ProtoMessage()    {}
func (*GameEntryPublic) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{2}
}
func (m *GameEntryPublic) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameEntryPublic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameEntryPublic.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GameEntryPublic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEntryPublic.Merge(dst, src)
}
func (m *GameEntryPublic) XXX_Size() int {
	return m.Size()
}
func (m *GameEntryPublic) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEntryPublic.DiscardUnknown(m)
}

var xxx_messageInfo_GameEntryPublic proto.InternalMessageInfo

func (m *GameEntryPublic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameEntryPublic) GetDur() string {
	if m != nil {
		return m.Dur
	}
	return ""
}

type SendPlayedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPlayedResponse) Reset()         { *m = SendPlayedResponse{} }
func (m *SendPlayedResponse) String() string { return proto.CompactTextString(m) }
func (*SendPlayedResponse) ProtoMessage()    {}
func (*SendPlayedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{3}
}
func (m *SendPlayedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SendPlayedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SendPlayedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SendPlayedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPlayedResponse.Merge(dst, src)
}
func (m *SendPlayedResponse) XXX_Size() int {
	return m.Size()
}
func (m *SendPlayedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPlayedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendPlayedResponse proto.InternalMessageInfo

type GetPlayedRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayedRequest) Reset()         { *m = GetPlayedRequest{} }
func (m *GetPlayedRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayedRequest) ProtoMessage()    {}
func (*GetPlayedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{4}
}
func (m *GetPlayedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPlayedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPlayedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetPlayedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayedRequest.Merge(dst, src)
}
func (m *GetPlayedRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetPlayedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayedRequest proto.InternalMessageInfo

func (m *GetPlayedRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type GetPlayedResponse struct {
	Games                []*GameEntryPublic `protobuf:"bytes,1,rep,name=games" json:"games,omitempty"`
	First                string             `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string             `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPlayedResponse) Reset()         { *m = GetPlayedResponse{} }
func (m *GetPlayedResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlayedResponse) ProtoMessage()    {}
func (*GetPlayedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{5}
}
func (m *GetPlayedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPlayedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPlayedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetPlayedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayedResponse.Merge(dst, src)
}
func (m *GetPlayedResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetPlayedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayedResponse proto.InternalMessageInfo

func (m *GetPlayedResponse) GetGames() []*GameEntryPublic {
	if m != nil {
		return m.Games
	}
	return nil
}

func (m *GetPlayedResponse) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *GetPlayedResponse) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

type AddUserRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{6}
}
func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(dst, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return m.Size()
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type AddUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{7}
}
func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(dst, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

type RemoveUserRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserRequest) Reset()         { *m = RemoveUserRequest{} }
func (m *RemoveUserRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveUserRequest) ProtoMessage()    {}
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{8}
}
func (m *RemoveUserRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveUserRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RemoveUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserRequest.Merge(dst, src)
}
func (m *RemoveUserRequest) XXX_Size() int {
	return m.Size()
}
func (m *RemoveUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserRequest proto.InternalMessageInfo

func (m *RemoveUserRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type RemoveUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserResponse) Reset()         { *m = RemoveUserResponse{} }
func (m *RemoveUserResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveUserResponse) ProtoMessage()    {}
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{9}
}
func (m *RemoveUserResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveUserResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RemoveUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserResponse.Merge(dst, src)
}
func (m *RemoveUserResponse) XXX_Size() int {
	return m.Size()
}
func (m *RemoveUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserResponse proto.InternalMessageInfo

type CheckWhitelistRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWhitelistRequest) Reset()         { *m = CheckWhitelistRequest{} }
func (m *CheckWhitelistRequest) String() string { return proto.CompactTextString(m) }
func (*CheckWhitelistRequest) ProtoMessage()    {}
func (*CheckWhitelistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{10}
}
func (m *CheckWhitelistRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckWhitelistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckWhitelistRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CheckWhitelistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWhitelistRequest.Merge(dst, src)
}
func (m *CheckWhitelistRequest) XXX_Size() int {
	return m.Size()
}
func (m *CheckWhitelistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWhitelistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWhitelistRequest proto.InternalMessageInfo

func (m *CheckWhitelistRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type CheckWhiteListResponse struct {
	Whitelisted          bool     `protobuf:"varint,1,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWhiteListResponse) Reset()         { *m = CheckWhiteListResponse{} }
func (m *CheckWhiteListResponse) String() string { return proto.CompactTextString(m) }
func (*CheckWhiteListResponse) ProtoMessage()    {}
func (*CheckWhiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_played_1611aaeebfa1a5bc, []int{11}
}
func (m *CheckWhiteListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CheckWhiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CheckWhiteListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CheckWhiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWhiteListResponse.Merge(dst, src)
}
func (m *CheckWhiteListResponse) XXX_Size() int {
	return m.Size()
}
func (m *CheckWhiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWhiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWhiteListResponse proto.InternalMessageInfo

func (m *CheckWhiteListResponse) GetWhitelisted() bool {
	if m != nil {
		return m.Whitelisted
	}
	return false
}

func init() {
	proto.RegisterType((*SendPlayedRequest)(nil), "played.SendPlayedRequest")
	proto.RegisterType((*GameEntry)(nil), "played.GameEntry")
	proto.RegisterType((*GameEntryPublic)(nil), "played.GameEntryPublic")
	proto.RegisterType((*SendPlayedResponse)(nil), "played.SendPlayedResponse")
	proto.RegisterType((*GetPlayedRequest)(nil), "played.GetPlayedRequest")
	proto.RegisterType((*GetPlayedResponse)(nil), "played.GetPlayedResponse")
	proto.RegisterType((*AddUserRequest)(nil), "played.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "played.AddUserResponse")
	proto.RegisterType((*RemoveUserRequest)(nil), "played.RemoveUserRequest")
	proto.RegisterType((*RemoveUserResponse)(nil), "played.RemoveUserResponse")
	proto.RegisterType((*CheckWhitelistRequest)(nil), "played.CheckWhitelistRequest")
	proto.RegisterType((*CheckWhiteListResponse)(nil), "played.CheckWhiteListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Played service

type PlayedClient interface {
	SendPlayed(ctx context.Context, opts ...grpc.CallOption) (Played_SendPlayedClient, error)
	GetPlayed(ctx context.Context, in *GetPlayedRequest, opts ...grpc.CallOption) (*GetPlayedResponse, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error)
	CheckWhitelist(ctx context.Context, in *CheckWhitelistRequest, opts ...grpc.CallOption) (*CheckWhiteListResponse, error)
}

type playedClient struct {
	cc *grpc.ClientConn
}

func NewPlayedClient(cc *grpc.ClientConn) PlayedClient {
	return &playedClient{cc}
}

func (c *playedClient) SendPlayed(ctx context.Context, opts ...grpc.CallOption) (Played_SendPlayedClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Played_serviceDesc.Streams[0], "/played.Played/SendPlayed", opts...)
	if err != nil {
		return nil, err
	}
	x := &playedSendPlayedClient{stream}
	return x, nil
}

type Played_SendPlayedClient interface {
	Send(*SendPlayedRequest) error
	CloseAndRecv() (*SendPlayedResponse, error)
	grpc.ClientStream
}

type playedSendPlayedClient struct {
	grpc.ClientStream
}

func (x *playedSendPlayedClient) Send(m *SendPlayedRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playedSendPlayedClient) CloseAndRecv() (*SendPlayedResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendPlayedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playedClient) GetPlayed(ctx context.Context, in *GetPlayedRequest, opts ...grpc.CallOption) (*GetPlayedResponse, error) {
	out := new(GetPlayedResponse)
	err := c.cc.Invoke(ctx, "/played.Played/GetPlayed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playedClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/played.Played/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playedClient) RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error) {
	out := new(RemoveUserResponse)
	err := c.cc.Invoke(ctx, "/played.Played/RemoveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playedClient) CheckWhitelist(ctx context.Context, in *CheckWhitelistRequest, opts ...grpc.CallOption) (*CheckWhiteListResponse, error) {
	out := new(CheckWhiteListResponse)
	err := c.cc.Invoke(ctx, "/played.Played/CheckWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Played service

type PlayedServer interface {
	SendPlayed(Played_SendPlayedServer) error
	GetPlayed(context.Context, *GetPlayedRequest) (*GetPlayedResponse, error)
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	RemoveUser(context.Context, *RemoveUserRequest) (*RemoveUserResponse, error)
	CheckWhitelist(context.Context, *CheckWhitelistRequest) (*CheckWhiteListResponse, error)
}

func RegisterPlayedServer(s *grpc.Server, srv PlayedServer) {
	s.RegisterService(&_Played_serviceDesc, srv)
}

func _Played_SendPlayed_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayedServer).SendPlayed(&playedSendPlayedServer{stream})
}

type Played_SendPlayedServer interface {
	SendAndClose(*SendPlayedResponse) error
	Recv() (*SendPlayedRequest, error)
	grpc.ServerStream
}

type playedSendPlayedServer struct {
	grpc.ServerStream
}

func (x *playedSendPlayedServer) SendAndClose(m *SendPlayedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playedSendPlayedServer) Recv() (*SendPlayedRequest, error) {
	m := new(SendPlayedRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Played_GetPlayed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayedServer).GetPlayed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/played.Played/GetPlayed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayedServer).GetPlayed(ctx, req.(*GetPlayedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Played_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayedServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/played.Played/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayedServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Played_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayedServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/played.Played/RemoveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayedServer).RemoveUser(ctx, req.(*RemoveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Played_CheckWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayedServer).CheckWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/played.Played/CheckWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayedServer).CheckWhitelist(ctx, req.(*CheckWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Played_serviceDesc = grpc.ServiceDesc{
	ServiceName: "played.Played",
	HandlerType: (*PlayedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayed",
			Handler:    _Played_GetPlayed_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Played_AddUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _Played_RemoveUser_Handler,
		},
		{
			MethodName: "CheckWhitelist",
			Handler:    _Played_CheckWhitelist_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendPlayed",
			Handler:       _Played_SendPlayed_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "played.proto",
}

func (m *SendPlayedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendPlayedRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.User)))
		i += copy(dAtA[i:], m.User)
	}
	if len(m.Game) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.Game)))
		i += copy(dAtA[i:], m.Game)
	}
	return i, nil
}

func (m *GameEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Dur != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(m.Dur))
	}
	return i, nil
}

func (m *GameEntryPublic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameEntryPublic) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Dur) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.Dur)))
		i += copy(dAtA[i:], m.Dur)
	}
	return i, nil
}

func (m *SendPlayedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SendPlayedResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *GetPlayedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPlayedRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.User)))
		i += copy(dAtA[i:], m.User)
	}
	return i, nil
}

func (m *GetPlayedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPlayedResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Games) > 0 {
		for _, msg := range m.Games {
			dAtA[i] = 0xa
			i++
			i = encodeVarintPlayed(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.First) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.First)))
		i += copy(dAtA[i:], m.First)
	}
	if len(m.Last) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.Last)))
		i += copy(dAtA[i:], m.Last)
	}
	return i, nil
}

func (m *AddUserRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddUserRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.User)))
		i += copy(dAtA[i:], m.User)
	}
	return i, nil
}

func (m *AddUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddUserResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *RemoveUserRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveUserRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.User)))
		i += copy(dAtA[i:], m.User)
	}
	return i, nil
}

func (m *RemoveUserResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveUserResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *CheckWhitelistRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckWhitelistRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintPlayed(dAtA, i, uint64(len(m.User)))
		i += copy(dAtA[i:], m.User)
	}
	return i, nil
}

func (m *CheckWhiteListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CheckWhiteListResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Whitelisted {
		dAtA[i] = 0x8
		i++
		if m.Whitelisted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func encodeVarintPlayed(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *SendPlayedRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	l = len(m.Game)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	return n
}

func (m *GameEntry) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	if m.Dur != 0 {
		n += 1 + sovPlayed(uint64(m.Dur))
	}
	return n
}

func (m *GameEntryPublic) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	l = len(m.Dur)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	return n
}

func (m *SendPlayedResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *GetPlayedRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	return n
}

func (m *GetPlayedResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.Games) > 0 {
		for _, e := range m.Games {
			l = e.Size()
			n += 1 + l + sovPlayed(uint64(l))
		}
	}
	l = len(m.First)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	l = len(m.Last)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	return n
}

func (m *AddUserRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	return n
}

func (m *AddUserResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *RemoveUserRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	return n
}

func (m *RemoveUserResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *CheckWhitelistRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovPlayed(uint64(l))
	}
	return n
}

func (m *CheckWhiteListResponse) Size() (n int) {
	var l int
	_ = l
	if m.Whitelisted {
		n += 2
	}
	return n
}

func sovPlayed(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPlayed(x uint64) (n int) {
	return sovPlayed(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SendPlayedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendPlayedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendPlayedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Game", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Game = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dur", wireType)
			}
			m.Dur = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Dur |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameEntryPublic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameEntryPublic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameEntryPublic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dur", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dur = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SendPlayedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SendPlayedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SendPlayedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetPlayedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPlayedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPlayedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetPlayedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPlayedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPlayedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Games", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Games = append(m.Games, &GameEntryPublic{})
			if err := m.Games[len(m.Games)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.First = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Last", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Last = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddUserRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddUserRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddUserRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveUserRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveUserRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveUserRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveUserResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveUserResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveUserResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckWhitelistRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckWhitelistRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckWhitelistRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayed
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CheckWhiteListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CheckWhiteListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CheckWhiteListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelisted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Whitelisted = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipPlayed(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPlayed
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPlayed(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPlayed
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlayed
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPlayed
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPlayed
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPlayed(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPlayed = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPlayed   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("played.proto", fileDescriptor_played_1611aaeebfa1a5bc) }

var fileDescriptor_played_1611aaeebfa1a5bc = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x4d, 0x5a, 0x5b, 0xcd, 0x7d, 0xf2, 0xde, 0xcb, 0x25, 0xbe, 0xa6, 0x01, 0x43, 0x09, 0xa2,
	0x05, 0xb1, 0x60, 0x5d, 0x08, 0xea, 0xc6, 0x4a, 0xe9, 0xc6, 0x45, 0x8d, 0x88, 0xe0, 0x2e, 0x6d,
	0x46, 0x1b, 0x4c, 0x93, 0x98, 0x99, 0x28, 0xfd, 0x17, 0xfe, 0x2c, 0x97, 0xfe, 0x04, 0xa9, 0x6b,
	0xff, 0x83, 0x4c, 0x66, 0xf2, 0xd1, 0x26, 0xb4, 0xbb, 0x3b, 0x77, 0xce, 0xb9, 0x73, 0xee, 0x39,
	0x09, 0xdc, 0x4d, 0x42, 0x6f, 0x47, 0xfc, 0x49, 0x92, 0xc6, 0x2c, 0xc6, 0xbe, 0x38, 0x39, 0x2f,
	0x41, 0x7f, 0x4f, 0x22, 0x7f, 0x99, 0x9f, 0x5c, 0xf2, 0x2d, 0x23, 0x94, 0x21, 0xc2, 0xad, 0x8c,
	0x92, 0xd4, 0x54, 0x47, 0xea, 0x58, 0x73, 0xf3, 0x9a, 0xf7, 0xbe, 0x78, 0x5b, 0x62, 0x76, 0x44,
	0x8f, 0xd7, 0xce, 0x53, 0xd0, 0x16, 0xde, 0x96, 0xcc, 0x23, 0x96, 0xee, 0x38, 0x20, 0xe2, 0x00,
	0x49, 0xe2, 0x35, 0x5e, 0x43, 0xd7, 0xcf, 0xd2, 0x9c, 0xd3, 0x73, 0x79, 0xe9, 0x3c, 0x87, 0xab,
	0x92, 0xb2, 0xcc, 0x56, 0x61, 0xb0, 0x3e, 0x47, 0xd4, 0x04, 0xd1, 0x00, 0xac, 0x0b, 0xa5, 0x49,
	0x1c, 0x51, 0xe2, 0x3c, 0x84, 0xeb, 0x05, 0x61, 0x67, 0xd5, 0x3b, 0x21, 0xe8, 0x35, 0x9c, 0x20,
	0xe3, 0x13, 0xe8, 0xf1, 0x35, 0xa8, 0xa9, 0x8e, 0xba, 0xe3, 0x8b, 0xe9, 0x60, 0x22, 0x1d, 0x3a,
	0x12, 0xe8, 0x0a, 0x14, 0x1a, 0xd0, 0xfb, 0x1c, 0xa4, 0x94, 0x49, 0x55, 0xe2, 0xc0, 0x5f, 0x0b,
	0x3d, 0xca, 0xcc, 0xae, 0x78, 0x8d, 0xd7, 0xce, 0x03, 0xb8, 0x7c, 0xed, 0xfb, 0x1f, 0x28, 0x49,
	0x4f, 0x69, 0xd2, 0xe1, 0xaa, 0x44, 0xc9, 0x75, 0x1e, 0x81, 0xee, 0x92, 0x6d, 0xfc, 0x9d, 0x9c,
	0xe3, 0x1a, 0x80, 0x75, 0xa0, 0xa4, 0x3f, 0x86, 0x7b, 0x6f, 0x36, 0x64, 0xfd, 0xf5, 0xe3, 0x26,
	0x60, 0x24, 0x0c, 0x28, 0x3b, 0x35, 0xe2, 0x05, 0xdc, 0x54, 0xe0, 0xb7, 0x39, 0x58, 0xfa, 0x32,
	0x82, 0x8b, 0x1f, 0xc5, 0x04, 0xe2, 0xe7, 0xa4, 0x3b, 0x6e, 0xbd, 0x35, 0xfd, 0xd7, 0x81, 0xbe,
	0x30, 0x13, 0x17, 0x00, 0x55, 0x2e, 0x38, 0x2c, 0x3c, 0x6c, 0x7c, 0x54, 0x96, 0xd5, 0x76, 0x25,
	0x85, 0x2b, 0x63, 0x15, 0x67, 0xa0, 0x95, 0x11, 0xa1, 0x59, 0x66, 0x71, 0x94, 0xae, 0x35, 0x6c,
	0xb9, 0x29, 0xa6, 0xe0, 0x2b, 0xb8, 0x2d, 0x2d, 0xc5, 0x9b, 0x02, 0x77, 0x98, 0x84, 0x35, 0x68,
	0xf4, 0x4b, 0xf6, 0x1c, 0xa0, 0x32, 0xb5, 0x5a, 0xa5, 0x91, 0x48, 0xb5, 0x4a, 0x4b, 0x06, 0x0a,
	0xbe, 0x83, 0xcb, 0xc3, 0x14, 0xf0, 0x7e, 0x81, 0x6f, 0x4d, 0xc7, 0xb2, 0x9b, 0xd7, 0xf5, 0x3c,
	0x1c, 0x65, 0x66, 0xfc, 0xda, 0xdb, 0xea, 0xef, 0xbd, 0xad, 0xfe, 0xd9, 0xdb, 0xea, 0xcf, 0xbf,
	0xb6, 0xf2, 0xa9, 0x93, 0xac, 0x56, 0xfd, 0xfc, 0x57, 0x7e, 0xf6, 0x3f, 0x00, 0x00, 0xff, 0xff,
	0xb7, 0xcb, 0xa1, 0xc6, 0xda, 0x03, 0x00, 0x00,
}
